name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        uses: docker://dataformco/dataform:1.6.11
        with:
          args: install
      - name: Decrypt dataform credentials
        run: gpg --quiet --batch --yes --decrypt --passphrase="$CREDENTIALS_GPG_PASSPHRASE" --output .df-credentials.json df-credentials.json.gpg
        env:
          CREDENTIALS_GPG_PASSPHRASE: ${{secrets.CREDENTIALS_GPG_PASSPHRASE}}

      - name: set defaults
        run: dataform init bigquery --default-location US --default-database cf-data-analytics
        uses: docker://dataformco/dataform:1.6.11

      - name: Execute dataform run
        uses: docker://dataformco/dataform:1.6.11
        with:
          args: run
